### PR TITLE
Rename Astra to Astra DB across the docs

### PR DESCRIPTION
**Pull request by erichare**
All references to Astra have been changed to Astra DB for consistency. Corresponding open source PR here: https://github.com/Unstructured-IO/unstructured/pull/3448

### CODE REVIEW

**Comment by Paul-Cornell** [comment]
Pulled remote branch, built locally, and spot-checked, seeing no obvious issues.

**Review by Paul-Cornell — APPROVED** [review]

**Comment by erichare** [comment]
@Paul-Cornell thanks for the quick review on this! If the docs go live as a result of the merge, could https://github.com/Unstructured-IO/unstructured/pull/3448 be prioritized for review? Some of these changes depend on the updates here as well. Thanks so much

**Comment by Paul-Cornell** [comment]
@erichare You'd need to ask the folks who work on that repo.

**Comment by erichare** [comment]
@Paul-Cornell sure thing, will do. Thank you

**Pull request merged**
