### PR TITLE
Update api-parameters.mdx with applicable values

### PR DESCRIPTION
**Pull request by ninalopatina**

### CODE REVIEW

**Review by scanny — COMMENTED** [review]
- I would ask Christine for review on this one as she'll know better than me.
- This mentions which file-types the parameter is active for but doesn't mention the set of possible valid values. Are there others besides "image" and "table"?
- What is an image block? Is that just a fancy name for an image? I'm pretty sure it's a layout-inference concept.
- It would be nice to make sense of how a table can be an image-block and why you can't get a table image out of say an HTML table or a PPTX table.

I think the gist of this concept is something like this:
> For PDF and Image file-types, layout-inference is used to distinguish rectangular sub-regions of a page (blocks) for items such as paragraphs, images, and tables. Add the detected rectangular page sub-page image for these block types to the element-metadata (in addition to OCR'ing them for text).

**Comment by ninalopatina** [comment]
@christinestraub  do you have more of the specifics that @scanny  mentioned above? I am not previously familiar with this parameter

**Comment by christinestraub** [comment]
@ninalopatina My suggestion is:
```
The types of elements to extract, for use in extracting image blocks as base64 encoded data stored in metadata fields. Example: ["image","table"]. Supported filetypes are Image, PDF and some Office (PPTX, PPT, DOCX, DOC, and ODT) files. For "table" image extraction, it is only supported for Image and PDF files.
```

**Review by Paul-Cornell — APPROVED** [review]

**Comment by Paul-Cornell** [comment]
I incorporated the proposal from @christinestraub and then got approval from @ninalopatina to merge.

**Pull request merged**
