### PR TITLE
minor updates re api url

### PR DESCRIPTION
**Pull request by MKhalusova**
Rephrased mentions of the API URL to avoid confusion.

### CODE REVIEW

**Comment by awalker4** [comment]
Can we also replace YOUR_API_URL in the code snippets?

**Comment by MKhalusova** [comment]
@awalker4 weird. I did that in the previous PR, must've been overwritten with some merge. I'll fix it

**Comment by MKhalusova** [comment]
@awalker4 where do you see it? It is `API_URL` and `YOUR_API_KEY` in this doc.

**Comment by MKhalusova** [comment]
Oh, you mean the actual URL. I think we should to leave it as `API_URL` since we pass it as a parameter and allow copying from dashboard.   I would advise against hardcoding it in the docs.

**Review by awalker4 — APPROVED** [review]

**Pull request merged**
