### PR TITLE
Add Couchbase Connector Docs

### PR DESCRIPTION
**Pull request by lokesh-couchbase**
Main Connector PR - https://github.com/Unstructured-IO/unstructured/pull/3292

### CODE REVIEW

**Comment by Paul-Cornell** [comment]
@lokesh-couchbase To clarify, this is only supported by Python Ingest SDK v1, correct? No Python Ingest SDK v2 support?

**Comment by lokesh-couchbase** [comment]
@Paul-Cornell , I don't think we support v2 yet. We will however love to be part of v2 apis as well

**Comment by Paul-Cornell** [comment]
@lokesh-couchbase just confirming with you after I spoke with @rbiseck3 that you plan to move to Python Ingest SDK v2 and then re-do this PR?

**Comment by lokesh-couchbase** [comment]
@Paul-Cornell , @rbiseck3 Is it possible to have v1 merged first and then we also raise the PR for v2?

**Pull request closed without merging**
