### PR TITLE
Use 'content type' to specify the content type to use

### PR DESCRIPTION
**Pull request by Paul-Cornell**
See the `content_type/contentType` row in the first table in https://unstructured-53-docs-18-content-type.mintlify.app/api-reference/api-services/api-parameters

### CODE REVIEW

**Comment by cragwolfe** [comment]
if you can prove it works against the API, lgtm! :)

**Comment by awalker4** [comment]
The `-F "files=@path/to/file.txt;type=text/plain"` is a bit of a one off since this is just a curl directive to set the `Content-Type` header. So it's not an API param on the same level of the others in the table. That being said, it would probably make our lives easier if we did just add `content_type` as an API param. I was avoiding it because we've been able to use the header, like with curl, or when sending a requests call, like this:

```
with open(file_path, 'rb') as file:
    files = {'file': ('file.txt', file, 'text/plain')}
    response = requests.post(url, files=files)
```

The SDKs don't have a way to set the header like this (yet). While we wait, though, an extra api param will get the job done.

So, next steps:
* @Paul-Cornell you can update the pr to say `content_type`, and it will be available in both columns
* I'll add the param to the API, and when the change is deployed, the python and typescript SDKs will pick up the new param
* Once the new SDKs are released, we can merge this PR

How's this all sound?

**Comment by Paul-Cornell** [comment]
@awalker4 OK, I updated `type` to `content_type/contentType`. Shall I merge?

**Comment by awalker4** [comment]
The clients should have the param by EOD so I'd say go for it! 🙏

**Comment by Paul-Cornell** [comment]
@awalker4 Could you please approve this PR, to unblock me from merging?

**Review by awalker4 — APPROVED** [review]

**Pull request merged**
